# Generated by Django 5.0.6 on 2024-07-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comuna",
            name="nombre",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="region",
            name="nombre",
            field=models.CharField(max_length=200),
        ),
    ]
