# Generated by Django 5.0.6 on 2024-06-18 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tarea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField(default="", max_length=500)),
                ("eliminada", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="SubTarea",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("descripcion", models.TextField(default="", max_length=500)),
                ("eliminada", models.BooleanField(default=False)),
                (
                    "tarea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="desafioadl.tarea",
                    ),
                ),
            ],
        ),
    ]
